browserType=Chrome
applicationUrl=https://automationexercise.com
incognitoMode=enabled
fullScreenMode=enabled
pageLoadWait=30
explicitWait=10
emailReport=disabled
reportSenderGmail=
reportSenderAppPassword=
reportReceiverGmail=